export const createReimbTypes = {
    UPDATE_AMOUNT: 'UPDATE_AMOUNT',
    UPDATE_AUTHOR: 'UPDATE_AUTHOR',
    UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION',
    UPDATE_SUBMITTED: 'UPDATE_SUBMITTED',
    UPDATE_TYPE_ID: 'UPDATE_TYPE_ID',
}